name: Deploy Azure Function
description: 'Deploy a .NET project to Azure Function'

inputs:
  azure-function-app-name:
    required: true
    type: string
  azure-function-package-path:
    required: true
    type: string
  artifact-name:
    default: 'drop'
    type: string
  arm-credentials:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.azure-function-package-path }}

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ inputs.arm-credentials }}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: azure-functions
      with:
        app-name: ${{ inputs.azure-function-app-name }}
        package: ${{ inputs.azure-function-package-path }}