parameters:
- name: EnvironmentName
  type: string
  default: ''
- name: AzureSubscription
  type: string
  default: ''
- name: AzureFunctionName
  type: string
  default: ''
- name: ArtifactName
  type: string
  default: 'drop'

jobs:
  - deployment: deploy_azure_function
    environment: ${{ parameters.EnvironmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            displayName: Download Web Application Artifact
            artifact: ${{ parameters.ArtifactName }}

          - task: AzureFunctionApp@2
            inputs:
              connectedServiceNameARM: '${{ parameters.AzureSubscription }}'
              appType: 'functionApp'
              appName: '${{ parameters.AzureFunctionName }}'
              package: $(System.ArtifactsDirectory)/**/*.zip
              deploymentMethod: 'auto'
