parameters:
- name: TerraformWorkingDirectory
  default: ''
- name: AzureServiceConnectionName
  default: ''
  description: 'Azure Service Connection Name'
- name: AzureResourceGroupName
  default: ''
  description: 'Resource Group Name for Terraform State And Azure Function'
- name: StorageAccountsName
  default: ''
  description: 'Storage Account Name for Terraform State'
- name: AzureContainerName
  default: ''
  description: 'Container Name for Terraform State'
- name: AzureRmKeyTFState
  default: ''
  description: 'FileName for Terraform State'
- name: EnvironmentName
  default: 'Test'
- name: Location
  default: 'SouthEast Asia'
- name: FuncStorageAccountName
  default: ''
  description: 'Storage Account Name for Azure Function'
- name: AzureFunctionName
  default: ''

jobs:
- job: ${{ parameters.EnvironmentName }}_Infra_Terraform
  steps:
  - task: TerraformInstaller@0
    displayName: "install"
    inputs:
      terraformVersion: '1.5.6'

  - task: TerraformTaskV3@3
    displayName: 'Terraform Init'
    inputs:
      workingDirectory: '${{ parameters.TerraformWorkingDirectory }}'
      provider: azurerm
      command: init
      commandOptions: '-lock=false'
      backendServiceArm: '${{ parameters.AzureServiceConnectionName }}'
      backendAzureRmResourceGroupName: '${{ parameters.AzureResourceGroupName }}'
      backendAzureRmStorageAccountName: '${{ parameters.StorageAccountsName }}'
      backendAzureRmContainerName: '${{ parameters.AzureContainerName }}'
      backendAzureRmKey: '${{ parameters.AzureRmKeyTFState }}'

  - task: TerraformTaskV3@3
    displayName: 'validate'
    inputs:
      workingDirectory: '${{ parameters.TerraformWorkingDirectory }}'
      provider: 'azurerm'
      command: 'validate'

  - task: TerraformTaskV3@3
    displayName: 'Terraform Plan'
    inputs:
      workingDirectory: '${{ parameters.TerraformWorkingDirectory }}'
      provider: 'azurerm'
      environmentServiceNameAzureRM: '${{ parameters.AzureServiceConnectionName }}'
      command: 'plan'
      commandOptions: '-var "environment=${{ parameters.EnvironmentName }}" -var "resource_group_name=${{ parameters.AzureResourceGroupName }}" -var "location=${{ parameters.Location }}" -var "functionapp_storage_account_name=${{ parameters.FuncStorageAccountName }}" -var "azurerm_windows_function_app_name=${{ parameters.AzureFunctionName }}" -input=false'

  - task: TerraformTaskV3@3
    displayName: 'Terraform Apply'
    inputs:
      workingDirectory: '${{ parameters.TerraformWorkingDirectory }}'
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: '${{ parameters.AzureServiceConnectionName }}'
      commandOptions: '-var "environment=${{ parameters.EnvironmentName }}" -var "resource_group_name=${{ parameters.AzureResourceGroupName }}" -var "location=${{ parameters.Location }}" -var "functionapp_storage_account_name=${{ parameters.FuncStorageAccountName }}" -var "azurerm_windows_function_app_name=${{ parameters.AzureFunctionName }}" -lock=false -auto-approve'
